#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/../lib/path-bootstrap.sh"
CONNECTOR_ROOT="${CONNECTOR_ROOT:-$FRAMEWORK_ROOT}"
REPO_ROOT="$CONNECTOR_ROOT"
. "$CI_ROOT/lib/common.sh"

blocked() {
    ci_blocked "prepare_crs $*"
    exit 77
}

ci_require_absolute_path "$CRS_SOURCE_DIR" "CRS_SOURCE_DIR" || exit 77
ci_require_absolute_path "$CRS_RUNTIME_DIR" "CRS_RUNTIME_DIR" || exit 77
assert_runtime_path_under_root "$CRS_SOURCE_DIR" "$SOURCE_ROOT" CRS_SOURCE_DIR || exit 77
assert_runtime_path_under_root "$CRS_RUNTIME_DIR" "$BUILD_ROOT" CRS_RUNTIME_DIR || exit 77
assert_safe_runtime_path "$CRS_RUNTIME_DIR" CRS_RUNTIME_DIR || exit 77

[ -d "$CRS_SOURCE_DIR" ] || blocked "missing CRS_SOURCE_DIR: $CRS_SOURCE_DIR; run make fetch-crs"
[ -f "$CRS_SOURCE_DIR/crs-setup.conf.example" ] || blocked "missing CRS setup template: $CRS_SOURCE_DIR/crs-setup.conf.example"
[ -d "$CRS_SOURCE_DIR/rules" ] || blocked "missing CRS rules directory: $CRS_SOURCE_DIR/rules"

set -- "$CRS_SOURCE_DIR"/rules/*.conf
[ -f "$1" ] || blocked "missing CRS rule files: $CRS_SOURCE_DIR/rules/*.conf"

mkdir -p "$CRS_RUNTIME_DIR"
cp "$CRS_SOURCE_DIR/crs-setup.conf.example" "$CRS_RUNTIME_DIR/crs-setup.conf"

preamble_file="$CRS_RUNTIME_DIR/modsecurity-crs-preamble.conf"
assert_not_system_path_for_write "$preamble_file" CRS_PREAMBLE_FILE || exit 77
{
    echo "# Generated by ci/provisioning/prepare-crs.sh. Do not edit."
    echo "Include \"$CRS_RUNTIME_DIR/crs-setup.conf\""
    if [ -d "$CRS_SOURCE_DIR/plugins" ]; then
        echo "Include \"$CRS_SOURCE_DIR/plugins/*-config.conf\""
        echo "Include \"$CRS_SOURCE_DIR/plugins/*-before.conf\""
    fi
    echo "Include \"$CRS_SOURCE_DIR/rules/*.conf\""
    if [ -d "$CRS_SOURCE_DIR/plugins" ]; then
        echo "Include \"$CRS_SOURCE_DIR/plugins/*-after.conf\""
    fi
} > "$preamble_file"

ci_info "prepare_crs ready MODSECURITY_RULE_PREAMBLE_FILE=$preamble_file"
