"""Closed rejection boundaries; all generated bytes here are unit fixtures only."""
from __future__ import annotations

import copy
import hashlib
from pathlib import Path
import tempfile
from types import SimpleNamespace
import unittest

from tests.no_crs.test_configtest_receipt import ConfigtestReceiptTest, no_crs


TARGETS = {
    'missing_rules_file': ('modsecurity_rules_file', 'missing-rules.conf'),
    'invalid_rule_syntax': ('modsecurity_rules', 'SecRule REQUEST_URI'),
    'unknown_config_key': ('modsecurity_unknown_config_key', 'on'),
    'unsafe_event_path': ('modsecurity_phase4_log', 'unsafe-event-directory'),
}


class ConfigtestTargetRejectionsTest(unittest.TestCase):
    def setUp(self):
        self.cases = {case['case_id']: case for case in no_crs.catalog_cases(no_crs.load_catalog())}
        temporary = tempfile.TemporaryDirectory(prefix='target-config-unit-')
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)

    def raw(self, case_id):
        invocation = no_crs.NGINX_CONFIGTEST_CONTRACTS[case_id]
        bundle = self.root / 'inventory/configtests' / case_id
        bundle.mkdir(parents=True, exist_ok=True)
        directive, value = TARGETS[case_id]
        receipt = ConfigtestReceiptTest.receipt()
        receipt.update(invocation, case_id=case_id)
        if case_id in {'missing_rules_file', 'unsafe_event_path'}:
            receipt.update(fixture_leaf=value, fixture_state='absent' if case_id == 'missing_rules_file' else 'directory')
            value = f'"{bundle}/{value}"'
        elif case_id == 'invalid_rule_syntax':
            value = f'"{value}"'
        if case_id == 'unsafe_event_path':
            (bundle / receipt['fixture_leaf']).mkdir(mode=0o700, exist_ok=True)
        config = (f'load_module "{bundle}/nginx-module.so";\n'
                  f'pid "{bundle}/nginx.pid";\n'
                  f'error_log "{bundle}/nginx-error.log";\n'
                  f'events {{}}\nhttp {{\n  {directive} {value};\n}}\n').encode()
        files = {'nginx-binary': ('binary_sha256', b'unit binary'),
                 'nginx-module.so': ('module_sha256', b'unit module'),
                 'nginx.conf': ('config_path_identity', config),
                 'stdout.log': ('stdout_sha256', b''),
                 'stderr.log': ('stderr_sha256', (' '.join(invocation['diagnostic_fragments'])
                                                 + (f' {bundle}/{receipt["fixture_leaf"]}' if 'fixture_leaf' in receipt else '')
                                                 + '\n').encode())}
        for name, (field, data) in files.items():
            (bundle / name).write_bytes(data)
            receipt[field] = ('sha256:' if name == 'nginx.conf' else '') + hashlib.sha256(data).hexdigest()
        raw = ConfigtestReceiptTest.raw()
        raw.update(case_id=case_id, configtest_receipt=receipt,
                   artifacts={'configtest_dir': 'inventory/configtests/' + case_id})
        return raw

    def normalize(self, raw):
        return no_crs.normalize_case_record(raw, 'nginx', self.cases, [], 'native-nginx-http-module',
                                            configtest_artifact_root=self.root)

    def test_four_required_records_have_explicit_closed_configtests(self):
        capabilities = {name: {'state': 'verified', 'reason': 'unit capability'} for name in no_crs.CAPABILITIES}
        for case_id, (directive, value) in TARGETS.items():
            with self.subTest(case_id=case_id):
                selection = no_crs.select_catalog_case(self.cases[case_id], capabilities, 'http1', 'nginx')
                self.assertEqual(selection['selection_status'], 'SELECTED')
                invocation = selection.get('config_invocation')
                self.assertIsNotNone(invocation, 'missing closed target configtest contract')
                self.assertEqual((invocation['operation'], invocation['directive'], invocation['value']),
                                 ('configtest', directive, value))

    def test_each_unit_bundle_validates_without_request_or_events(self):
        for case_id in TARGETS:
            with self.subTest(case_id=case_id):
                record = self.normalize(self.raw(case_id))
                self.assertEqual(record['status'], 'PASS', record['reason'])
                self.assertEqual(no_crs.pass_case_completeness_errors(
                    record, [], 'nginx', 'native-nginx-http-module', artifact_root=self.root), [])
                self.assertEqual(record['observed_rule_ids'], [])
                self.assertEqual(record['transaction_ids'], [])

    def test_wrong_identity_operation_reason_module_or_missing_raw_cannot_pass(self):
        for case_id in TARGETS:
            for field, value in [('case_id', 'invalid_boolean'), ('operation', 'startup'),
                                 ('run_id', 'foreign'), ('error_class', 'module_missing'),
                                 ('module_sha256', '0' * 64), ('observed_exit_code', 2),
                                 ('diagnostic_fragments', ['module is missing'])]:
                with self.subTest(case_id=case_id, field=field):
                    raw = self.raw(case_id)
                    raw['configtest_receipt'][field] = value
                    self.assertEqual(self.normalize(raw)['status'], 'FAIL')
            raw = self.raw(case_id)
            (self.root / raw['artifacts']['configtest_dir'] / 'stderr.log').unlink()
            self.assertEqual(self.normalize(raw)['status'], 'FAIL')

    def test_rehashed_wrong_config_or_diagnostic_cannot_pass(self):
        for case_id in TARGETS:
            for name, field, data in [('nginx.conf', 'config_path_identity', b'events {}\n'),
                                      ('stderr.log', 'stderr_sha256', b'unknown directive "load_module"\n')]:
                with self.subTest(case_id=case_id, name=name):
                    raw = self.raw(case_id)
                    (self.root / raw['artifacts']['configtest_dir'] / name).write_bytes(data)
                    raw['configtest_receipt'][field] = ('sha256:' if name == 'nginx.conf' else '') + hashlib.sha256(data).hexdigest()
                    self.assertEqual(self.normalize(raw)['status'], 'FAIL')

    def test_fixture_state_is_observed_and_cannot_be_relabelled(self):
        for case_id in ('missing_rules_file', 'unsafe_event_path'):
            for field, value in [('fixture_leaf', 'other'), ('fixture_state', 'regular')]:
                raw = self.raw(case_id)
                raw['configtest_receipt'][field] = value
                self.assertEqual(self.normalize(raw)['status'], 'FAIL')
            raw = self.raw(case_id)
            del raw['configtest_receipt']['fixture_state']
            self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        raw = self.raw('missing_rules_file')
        (self.root / raw['artifacts']['configtest_dir'] / 'missing-rules.conf').write_bytes(b'present')
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        raw = self.raw('unsafe_event_path')
        path = self.root / raw['artifacts']['configtest_dir'] / 'unsafe-event-directory'
        path.chmod(0o777)
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')

    def test_finalize_retains_private_fixture_and_absence_and_distinct_bundles(self):
        raws = [self.raw(case_id) for case_id in TARGETS]
        for raw in raws:
            raw['artifacts']['configtest_dir'] = str(self.root / raw['artifacts']['configtest_dir'])
        output = self.root / 'canonical'
        output.mkdir()
        context = SimpleNamespace(case_by_id=self.cases, connector='nginx', run_dir=output,
                                  event_integration_mode=None,
                                  configtest_source_roots={id(raw): self.root for raw in raws},
                                  configtest_copied_cases=set(),
                                  manifest={'artifacts': {}, 'integration_mode': 'native-nginx-http-module'})
        records = no_crs.normalized_finalize_case_records(context, raws, [])
        self.assertEqual([record['status'] for record in records], ['PASS'] * 4)
        self.assertFalse((output / 'inventory/configtests/missing_rules_file/missing-rules.conf').exists())
        self.assertTrue((output / 'inventory/configtests/unsafe_event_path/unsafe-event-directory').is_dir())
        for record in records:
            self.assertEqual(no_crs.configtest_artifact_errors(record, output), [])

    def test_unknown_record_receipt_and_not_executed_never_pass(self):
        raw = self.raw('unknown_config_key')
        raw['case_id'] = 'unregistered_config'
        self.assertIsNone(self.normalize(raw))
        raw = self.raw('unknown_config_key')
        raw.update(status='NOT_EXECUTED', live_executed=False)
        self.assertEqual(self.normalize(raw)['status'], 'NOT_EXECUTED')
        case = copy.deepcopy(self.cases['unknown_config_key'])
        case['case_id'] = 'unregistered_config'
        self.assertTrue(no_crs.config_invocation_contract_errors(case))

    def test_path_fixture_symlinks_regular_files_and_nonempty_directories_fail(self):
        raw = self.raw('missing_rules_file')
        path = self.root / raw['artifacts']['configtest_dir'] / 'missing-rules.conf'
        path.symlink_to('not-present')
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        raw = self.raw('unsafe_event_path')
        path = self.root / raw['artifacts']['configtest_dir'] / 'unsafe-event-directory'
        (path / 'unexpected').write_bytes(b'unit')
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        (path / 'unexpected').unlink()
        path.rmdir()
        path.write_bytes(b'unit')
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        path.unlink()
        path.symlink_to(self.root, target_is_directory=True)
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')

    def test_leaf_name_alone_in_diagnostic_and_extra_fixture_metadata_fail(self):
        for case_id in ('missing_rules_file', 'unsafe_event_path'):
            raw = self.raw(case_id)
            data = (' '.join(raw['configtest_receipt']['diagnostic_fragments']) + '\n').encode()
            (self.root / raw['artifacts']['configtest_dir'] / 'stderr.log').write_bytes(data)
            raw['configtest_receipt']['stderr_sha256'] = hashlib.sha256(data).hexdigest()
            self.assertEqual(self.normalize(raw)['status'], 'FAIL')
        raw = self.raw('invalid_rule_syntax')
        raw['configtest_receipt'].update(fixture_leaf='missing-rules.conf', fixture_state='absent')
        self.assertEqual(self.normalize(raw)['status'], 'FAIL')


if __name__ == '__main__':
    unittest.main()
