#!/usr/bin/env python3
"""Framework-owned generated report helpers.

Connector repositories are untrusted inputs for report generation; keep helper
code in this repository so generators never import executable connector code.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

SAFE_REPORT_NAMES = {
    "connector_work_queue",
    "phase_work_queue",
    "phase_coverage",
    "full_runtime_matrix",
    "runtime_component_cache",
    "mrts_native_full",
    "mrts_native_apache",
    "mrts_native_nginx",
    "mrts_native_summary",
}
SAFE_SUFFIXES = {"json", "md"}


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _as_posix(path: Path | str) -> str:
    return str(Path(path))


def build_metadata(*, generated_by: str, make_target: str, connector_root: Path | str, framework_root: Path | str, inputs: Iterable[Path | str], generated_at: str | None = None) -> dict[str, Any]:
    return {
        "generated_at": generated_at or utc_now(),
        "generated_by": generated_by,
        "make_target": make_target,
        "connector_root": _as_posix(connector_root),
        "framework_root": _as_posix(framework_root),
        "inputs": [_as_posix(item) for item in inputs],
    }


def report_path_from_root(root: Path | str, name: str, suffix: str) -> Path:
    if name not in SAFE_REPORT_NAMES:
        raise ValueError(f"unsupported generated report name: {name}")
    if suffix not in SAFE_SUFFIXES:
        raise ValueError(f"unsupported generated report suffix: {suffix}")
    base = Path(root).resolve()
    target = (base / "canonical" / f"{name}.generated.{suffix}").resolve()
    try:
        target.relative_to(base)
    except ValueError as exc:
        raise ValueError(f"generated report path escapes output root: {target}") from exc
    return target



def reject_path_traversal(value: Path | str, label: str) -> None:
    raw = str(value)
    path = Path(raw)
    if any(part in {"..", ""} for part in path.parts):
        raise ValueError(f"{label} contains unsafe traversal or empty path segment: {raw}")


def require_under(root: Path | str, candidate: Path | str, label: str) -> Path:
    reject_path_traversal(candidate, label)
    root_path = Path(root).resolve()
    candidate_path = Path(candidate)
    if not candidate_path.is_absolute():
        candidate_path = root_path / candidate_path
    resolved = candidate_path.resolve(strict=False)
    try:
        resolved.relative_to(root_path)
    except ValueError as exc:
        raise ValueError(f"{label} must stay under {root_path}: {resolved}") from exc
    parent = resolved.parent
    if parent.exists() and parent.resolve(strict=True) != parent.resolve(strict=False):
        raise ValueError(f"{label} parent resolves through an unsafe symlink: {parent}")
    try:
        parent.resolve(strict=True).relative_to(root_path)
    except (OSError, ValueError) as exc:
        raise ValueError(f"{label} parent must stay under {root_path}: {parent}") from exc
    return resolved

def generated_json_text(payload: Any, metadata: dict[str, Any]) -> str:
    document = {"metadata": metadata, "data": payload}
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def generated_markdown_text(body: str, metadata: dict[str, Any]) -> str:
    generated_at = metadata.get("generated_at", "")
    generated_by = metadata.get("generated_by", "")
    header = [
        "<!-- Generated file - do not edit manually. -->",
        f"> Generated at: `{generated_at}`",
        f"> Generated by: `{generated_by}`",
        "",
    ]
    return "\n".join(header) + body.rstrip() + "\n"
